
import React, { useState, useRef } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Download, Calendar, TrendingUp, Users, DollarSign, FileText, Globe, Printer, Mail } from 'lucide-react';
import { format, subDays } from 'date-fns';
import toast from 'react-hot-toast';
import html2pdf from 'html2pdf.js';

const Reports = () => {
  const { user, isCBLAdmin, isGroupLeader } = useAuth();
  const reportRef = useRef();
  const [reportType, setReportType] = useState('summary');
  const [dateRange, setDateRange] = useState({ start: format(subDays(new Date(), 30), 'yyyy-MM-dd'), end: format(new Date(), 'yyyy-MM-dd') });
  const [generating, setGenerating] = useState(false);

  const handleExportCSV = () => {
    toast.success('CSV Export feature - Would download transaction data');
    // Implement actual CSV export here
  };

  const handleExportJSON = () => {
    toast.success('JSON Export feature - Would download JSON data');
  };

  const handleGeneratePDF = async () => {
    setGenerating(true);
    toast.loading('Generating PDF...');
    try {
      const element = reportRef.current;
      const opt = { margin: [0.5, 0.5, 0.5, 0.5], filename: `VSLA_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`, image: { type: 'jpeg', quality: 0.98 }, html2canvas: { scale: 2 }, jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' } };
      await html2pdf().set(opt).from(element).save();
      toast.dismiss();
      toast.success('PDF Report generated!');
    } catch (err) {
      toast.error('Failed to generate PDF');
    } finally {
      setGenerating(false);
    }
  };

  const Letterhead = () => (
    <div className="text-center mb-8 pb-4 border-b-2 border-gray-300">
      <div className="flex justify-between items-center">
        <div className="text-left"><div className="text-2xl font-bold text-indigo-700">Republic of Liberia</div><div className="text-xl font-semibold">Central Bank of Liberia</div><div className="text-sm text-gray-600">Financial Inclusion Division</div></div>
        <div className="text-right"><div className="text-3xl font-bold">VSLA</div><div className="text-xs text-gray-500">Village Savings & Loan Association</div></div>
      </div>
      <div className="text-center text-xs text-gray-500 mt-2">P.O. Box 123, Monrovia, Liberia | Tel: +231-777-123-456 | www.cbl.gov.lr</div>
    </div>
  );

  const ReportFooter = () => (
    <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
      <p>This report is generated by the Central Bank of Liberia VSLA Management System</p>
      <p>Generated on: {format(new Date(), 'MMMM dd, yyyy h:mm a')}</p>
      <p className="mt-2">Authorized Signatory: _________________________</p>
    </div>
  );

  if (isCBLAdmin) {
    return (
      <div className="p-6 space-y-6">
        <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
          <div ref={reportRef} className="p-8 bg-white text-black" style={{ width: '210mm' }}>
            <Letterhead />
            <h1 className="text-2xl font-bold text-center mt-6">National VSLA Performance Report</h1>
            <p className="text-center text-gray-600 mb-6">Period: {format(new Date(dateRange.start), 'MMMM dd, yyyy')} - {format(new Date(dateRange.end), 'MMMM dd, yyyy')}</p>
            <div className="grid grid-cols-2 gap-4 mb-6"><div className="border p-4 rounded"><p className="text-gray-600">Total Groups</p><p className="text-2xl font-bold">4</p></div><div className="border p-4 rounded"><p className="text-gray-600">Active Members</p><p className="text-2xl font-bold">9</p></div><div className="border p-4 rounded"><p className="text-gray-600">Total Savings</p><p className="text-2xl font-bold">$1,134</p></div><div className="border p-4 rounded"><p className="text-gray-600">Repayment Rate</p><p className="text-2xl font-bold text-green-600">33%</p></div></div>
            <ReportFooter />
          </div>
        </div>

        <div className="flex justify-between items-center"><div><h1 className="text-2xl font-bold text-white">National Reports</h1><p className="text-gray-400 text-sm">Central Bank Analytics & Financial Inclusion Metrics</p></div><div className="flex gap-2"><button onClick={handleExportCSV} className="bg-gray-700 hover:bg-gray-600 px-4 py-2 rounded-lg text-white flex items-center gap-2"><Download size={16} /> CSV</button><button onClick={handleGeneratePDF} disabled={generating} className="bg-indigo-600 hover:bg-indigo-700 px-4 py-2 rounded-lg text-white flex items-center gap-2"><Printer size={16} /> {generating ? 'Generating...' : 'PDF Report'}</button></div></div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {[{ title: 'Financial Inclusion', value: '86%', change: '+12%', icon: Users }, { title: 'Women Participation', value: '64%', change: '+8%', icon: Users }, { title: 'Avg Savings/Member', value: '$289', change: '+5%', icon: DollarSign }, { title: 'Active Groups', value: '4', change: '+2', icon: Globe }].map((stat, i) => (
            <div key={i} className="bg-gray-800/50 rounded-xl p-4 border border-gray-700"><div className="flex justify-between"><div><p className="text-gray-400 text-sm">{stat.title}</p><p className="text-2xl font-bold text-white">{stat.value}</p><div className="flex items-center gap-1 mt-1 text-green-400 text-xs"><TrendingUp size={10} />{stat.change}</div></div><stat.icon size={20} className="text-gray-400" /></div></div>
          ))}
        </div>

        <div className="bg-gray-800/50 rounded-xl p-5 border border-gray-700"><h3 className="text-white font-semibold mb-4">Report Generator</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><div><label className="block text-xs text-gray-400 mb-1">Report Type</label><select value={reportType} onChange={(e) => setReportType(e.target.value)} className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white"><option value="summary">Executive Summary</option><option value="detailed">Detailed Analytics</option><option value="demographics">Demographics Report</option><option value="loan">Loan Performance</option></select></div><div><label className="block text-xs text-gray-400 mb-1">From Date</label><input type="date" value={dateRange.start} onChange={(e) => setDateRange({...dateRange, start: e.target.value})} className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white" /></div><div><label className="block text-xs text-gray-400 mb-1">To Date</label><input type="date" value={dateRange.end} onChange={(e) => setDateRange({...dateRange, end: e.target.value})} className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white" /></div></div><div className="flex gap-3"><button onClick={handleGeneratePDF} className="bg-indigo-600 text-white px-4 py-2 rounded-lg flex items-center gap-2"><FileText size={16} /> Generate Report</button><button onClick={handleExportCSV} className="border border-gray-600 text-gray-300 px-4 py-2 rounded-lg flex items-center gap-2"><Download size={16} /> Export CSV</button></div></div>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold text-white">{isGroupLeader ? 'Group Performance Report' : 'My Loan Statement'}</h1>
      <div className="bg-gray-800/50 rounded-xl p-5 border border-gray-700">
        <h3 className="text-white font-semibold mb-4">Report Options</h3>
        <div className="grid grid-cols-2 gap-4 mb-6"><div><label className="block text-xs text-gray-400 mb-1">From Date</label><input type="date" className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white" /></div><div><label className="block text-xs text-gray-400 mb-1">To Date</label><input type="date" className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white" /></div></div>
        <div className="flex gap-3"><button onClick={handleExportCSV} className="bg-indigo-600 text-white px-4 py-2 rounded-lg">Generate Report</button><button onClick={handleExportCSV} className="border border-gray-600 text-gray-300 px-4 py-2 rounded-lg">Export CSV</button></div>
      </div>
    </div>
  );
};

export default Reports;
